### ISSUE TITLE
Issue bar 애니메이션 시급

### ISSUE THREAD

**Issue by Rumo-Arf** [Rumo-Arf/surro#110]
가속도 적용한 progressbar 애니메이션을 구현해야함. 25일 중으로 프로토 타입 만들어서 성능 테스트도 하고...

**Comment by hj0212** [comment]
일단 기본적인 애니메이션 적용해놨음

**Comment by Rumo-Arf** [comment]
@hj0212 뭐지? 이번 커밋에는 없나? 없는 것 같은데..

**Comment by Rumo-Arf** [comment]
아, 아니다; 지금 뭔가 폴더가 꼬였다.. 수정함.
