### ISSUE TITLE
이슈바에 label 붙이기 한계 

### ISSUE THREAD

**Issue by Rumo-Arf** [Rumo-Arf/surro#111]
![default](https://cloud.githubusercontent.com/assets/11865340/13178367/ddd13456-d761-11e5-95ab-c70ddd125626.PNG)

저기에 라벨 더 들어가야하는데 그냥 대충 추가 했다간 div가 완전히 꼬인다... 이슈 재설꼐 하면서 반드시 해결하고 넘어가야 함.

**Comment by hj0212** [comment]
라벨 많이 달아봤자 두개밖에 안들어갈거같은데..
그럼 라벨 공간을 정해두고 필요하면 거기다 넣고 뭐 이렇게해야지

**Comment by Rumo-Arf** [comment]
2 * 2 식으로 행렬 배치 하더라도 라벨은 최대한 많이 넣을 수 있어야 할 것 같다.
전에 내가 억지로 라벨 넣어보니 라벨 사이즈 조절 하면 3개 까진 괜찮겠더라.

**Comment by Rumo-Arf** [comment]
@hj0212 Label에 Deadline 추가 가능할지?

**Comment by hj0212** [comment]
다른 애들이랑 똑같이? 지금 다른 애들은 다 두글잔데 데드라인은 두글자가 아닐거 아녀? 그럼 얘만 혼자 길텐데..

**Comment by Rumo-Arf** [comment]
@hj0212 정렬이 되지 않더라도 추가 하면 좋겠음. 그래도 의견을 달리한다면 다른 식으로 표현할 방법을 의논 해 보자.

**Comment by Rumo-Arf** [comment]
@hj0212 라벨은 deadline을 추가하여 2*2로 수정 결정. Responsive하지 않거나 배열이 흐트러지는 버그는 고려하지 않고 고속 프로토타이핑.

**Comment by Rumo-Arf** [comment]
#157 으로 이슈 이동
