### ISSUE TITLE
스레드 플로팅 시스템 효용성 의논

### ISSUE THREAD

**Issue by Rumo-Arf** [Rumo-Arf/surro#118]
국내 커뮤니티 게시글은 그냥 뭐 본문에 댓글 있고.. 그게 전부다.
2ch나 4chan과 같은 해외 커뮤니티의 글은 시간이 아무리 오래 지나도 새 댓글이 달리면
다시 1번 페이지 뷰로 올라오게 되는 시스템. 답글이 달리는 이상 그 글이 묻히는 일이 없으니까 
이슈 트래커에도 이런 시스템을 적용하는게 좋을 것 같음.
과거 Naver의 Xe도 해외 시장 진출에 지나치게 국내 지향이라 외쿡에서 인기를 못 얻었다는 지적도...

**Comment by hj0212** [comment]
끌올!

**Comment by Rumo-Arf** [comment]
@hj0212 스레드 플로팅 시스템 적용이유 정리했던거 좀 올려봐요. "끌올!" 말고.

**Comment by hj0212** [comment]
현재 국내의 게시판은 모두 아시다시피 본문이 있고.. 댓글이 있고 다들 그런 식임. 전형적이고 직관적이라서 알기 쉽지만 시간이 지나면 순서대로 글이 밀려나기 시작한다는 단점이 있음.
해외 포럼, 커뮤니티에서는 날짜 순이 아니라 댓글이 달리면 가장 상위로 올리는 시스템인데 덕분에 시간이 흘러도 댓글이 새로 달리면 상위에 보이게 됨.
가끔 해외 포럼에 들어가 보면 10년 전 어떤 글에는 댓글이 수백 수천개씩 달려있는데 오랜 시간 동안 집약된 정보량이 상당함.

**Comment by Rumo-Arf** [comment]
#178, 댓글이 달린 게시글이 상위로 올라가도록 DB ORDER 되어 있음.

**Comment by Rumo-Arf** [comment]
잘 구현 되어 있는 것 같음.
