### ISSUE TITLE
반응형 웹

### ISSUE THREAD

**Issue by hj0212** [Rumo-Arf/surro#124]
현재 [materializecss] (http://materializecss.com/) 를 사용하여 웹을 반응형으로 구현 중인데
사이즈를 줄였을 때 겹치거나 틀이 흐트러지는 부분들이 있음..많음..ㅠㅠ

이슈에 사진첨부 어떻게 하는..?ㅠㅠ

**Comment by Rumo-Arf** [comment]
@hj0212 사진 첨부 기능은 지금 죽여놓은 상태... 아니면 php코드를 말하는건가?

**Comment by Rumo-Arf** [comment]
반응형 에러나는 현상 스크린샷 첨부좀 ㅇㅇ..

**Comment by hj0212** [comment]
그래 반응형 에러나는 현상 스크린샷 첨부하는 방법..캡쳐해놨는데 올리질 못하네ㅋㅋㅋ

**Comment by hj0212** [comment]
![2016-02-25 11 29 26](https://cloud.githubusercontent.com/assets/15020143/13322481/ed1deb7e-dc17-11e5-982d-5c9198aad2f9.png)
![2016-02-25 11 31 03](https://cloud.githubusercontent.com/assets/15020143/13322486/f2a3e4c2-dc17-11e5-8fe7-31477e579325.png)

예를 들어서 이런..어떤건 모바일 크기일 때 망가지고 어떤건 태블릿 크기에서만 망가지고 수정이 필요해

**Comment by Rumo-Arf** [comment]
.... 일단 패스.

**Comment by Rumo-Arf** [comment]
이 이슈는 나중에 다시 오픈
