### ISSUE TITLE
미사용 기능 삭제 요청

### ISSUE THREAD

**Issue by Rumo-Arf** [Rumo-Arf/surro#141]
<img width="99" alt="2016-02-29 8 54 40" src="https://cloud.githubusercontent.com/assets/11865340/13393753/bbe00a80-df26-11e5-995c-ace0f5165598.png">

나머지 버튼은 사용 안하는 걸로 결정 났으니 삭제 바람..

**Comment by hj0212** [comment]
코드 수정 후 머지했음
