### ISSUE TITLE
이슈 바 Redesign 

### ISSUE THREAD

**Issue by Rumo-Arf** [Rumo-Arf/surro#146]
이슈 바의 두번 째 Redesign 고려 중. 프로토타입이 나오면 좋지만 일단은 재 설계가 필요할지 의견 바람.
IntelliJ tracker 예시 사진 첨부

![image](https://cloud.githubusercontent.com/assets/11865340/13545810/7ebe996a-e2db-11e5-9ed7-9dc53b2432b7.png)

**Comment by hj0212** [comment]
<img width="481" alt="2016-03-07 10 59 01" src="https://cloud.githubusercontent.com/assets/15020143/13571443/55428310-e4b8-11e5-9b6a-40fdd2928796.png">

따란~ 이슈바 ver 2.0

**Comment by Rumo-Arf** [comment]
아, 어. **_따란~;_**
