### ISSUE TITLE
CKEditor 도입 검토

### ISSUE THREAD

**Issue by Rumo-Arf** [Rumo-Arf/surro#148]
기타 다른 에디터 조사 후 의견 바람...

![image](https://cloud.githubusercontent.com/assets/11865340/13546257/d310686c-e2eb-11e5-9dbb-bed988dd287d.png)

http://ckeditor.com/demo

**Comment by Rumo-Arf** [comment]
급하게 적용 해 봤음. 

![image](https://cloud.githubusercontent.com/assets/11865340/13546298/22e1b3f4-e2ed-11e5-97d9-2ff5ede645d5.png)

**Comment by Rumo-Arf** [comment]
왠지 훨씬 더 깔끔하고 좋은 걸 찾았다.

http://quilljs.com/

![image](https://cloud.githubusercontent.com/assets/11865340/13546317/8ac1ceb4-e2ed-11e5-9bcd-849c6f27c4b8.png)

**Comment by hj0212** [comment]
이게 더 이쁘네ㅋㅋ적용샷 기다림ㄹㄹ

**Comment by Rumo-Arf** [comment]
Quills는 Getting Start부터 막혔다. 일단은 CKEdtor Push 하였음.

**Comment by Rumo-Arf** [comment]
CKEditor로 결정...
