### ISSUE TITLE
이슈 바 ver 2.0 개선안

### ISSUE THREAD

**Issue by Rumo-Arf** [Rumo-Arf/surro#157]
<img width="480" alt="kakaotalk_photo_2016-03-06-01-56-20" src="https://cloud.githubusercontent.com/assets/11865340/13548926/aa89519e-e33e-11e5-8bb6-c547a93b5ce4.png">

- [x] 작성자와 작성 날짜 구분
- [x] 라벨 색상 재조합

**Comment by hj0212** [comment]
<img width="481" alt="2016-03-07 10 59 01" src="https://cloud.githubusercontent.com/assets/15020143/13571486/a84d072e-e4b8-11e5-9439-de205ffa1df3.png">

작성자랑 작성 날짜 사이에 구분선 삽입
라벨 색상은 이거 별론가?

**Comment by Rumo-Arf** [comment]
버그랑 심각 색상이 동일해도 괜찮을까.

![image](https://cloud.githubusercontent.com/assets/11865340/13573313/80d25596-e4c2-11e5-9211-8e8711c47b59.png)

깃 허브의 라벵 색상 참고.

**Comment by hj0212** [comment]
<img width="484" alt="2016-03-08 12 28 48" src="https://cloud.githubusercontent.com/assets/15020143/13573833/e968a7f2-e4c4-11e5-8232-1a908b7fb06f.png">
버그 색상 수정 완료

**Comment by Rumo-Arf** [comment]
#183 최종 수정 완료
