### ISSUE TITLE
Pure.io 라이브러리 적용 및 Code Igniter 프레임 워크 투입

### ISSUE THREAD

**Issue by Rumo-Arf** [Rumo-Arf/surro#73]
더 이상은 해 본 적도 없는 웹 개발을 HTML5 / CSS3만으로 반응형 웹 개발을 하기엔 무리다.

Yahoo에서 개발한 Responsive Layout CSS 라이브러리 Pure.io 적용 검토 바람.

이 외에도 Page transition할 때 필요한 Animation도 구해보자.,..

**Comment by Rumo-Arf** [comment]
Code Igniter 적용 중. 아직까지는 문제 없음.

**Comment by Rumo-Arf** [comment]
그동안 열심히 일 해준 Pure에게 감사합니다. 워낙 좋은 라이브리들이 많아서 당신은 이제 필요하지 않을 것 같습니다. 다음 업데이트 때 없어질 듯..

**Comment by hj0212** [comment]
안녕 퓨어...

**Comment by Rumo-Arf** [comment]
Pure io 삭제 하였음.
