### ISSUE TITLE
디자인 컨셉 수정 [ Flat Design -> Material Design ]

### ISSUE THREAD

**Issue by hj0212** [Rumo-Arf/surro#77]
### **Flat Design에서 벗어나 Material Design으로 디자인 컨셉 전면 수정.**

 1. 유행을 따라 적용한 Flat Design을 구글의 Material Design을 참조하여 전면 수정하고
    사용자와 소통할 수 있는 반응형 웹, 어플을 만든다. (library 적극 활용할 것)
 2. 사용자와의 간결하고 직관적인 의사소통을 위해 아이콘을 적극 활용한다.

**Comment by hj0212** [comment]
### **참고사이트**
 구글 Material Design GuideLines [https://www.google.com/design/spec/material- design/introduction.html#](https://www.google.com/design/spec/material-design/introduction.html#)
 구글 Material Design github [https://github.com/google/material-design-lite](https://github.com/google/material-design-lite)
 Material Design 소개글 [https://brunch.co.kr/@yunjungseo/3](https://brunch.co.kr/@yunjungseo/3)
 materializecss [http://materializecss.com/about.html](http://materializecss.com/about.html)
 material-ui [http://www.material-ui.com/#/](http://www.material-ui.com/#/)
 구글 Color palette [https://www.google.com/design/spec/style/color.html#](https://www.google.com/design/spec/style/color.html#)

**Comment by Rumo-Arf** [comment]
일단 Google에서 개설한 github는 이거..
https://github.com/google/material-design-lite
그런데 지나치게 구글을 표방하게 되지 않을까... Materializecss를 쓰는 게 더 나을까? -,.-;

**Comment by Rumo-Arf** [comment]
지나고 나서 생각 해보니 요즘은 또 전부 다 Material Design이네...

**Comment by hj0212** [comment]
내말이...아는만큼 보인다고..몰랐었는데 어플들도 전부 material인 듯

**Comment by Rumo-Arf** [comment]
지금 이슈 쓰기 버튼은 지나치게 메테리얼인데... 이슈 쓰기 버튼 다른 디자인으로 배치 하는 걸 고려 해 봤으면 함.
<img width="88" alt="2016-02-25 11 20 49" src="https://cloud.githubusercontent.com/assets/11865340/13307847/daa45052-dbb1-11e5-9e0c-7e76c0d3be0e.png">

**Comment by Rumo-Arf** [comment]
버튼 유지, 메테리얼 컨셉으로 수정 끝.
