### ISSUE TITLE
Tabs에 스크롤 생기는 버그가...

### ISSUE THREAD

**Issue by Rumo-Arf** [Rumo-Arf/surro#82]
![default](https://cloud.githubusercontent.com/assets/11865340/12693835/64b6ecc0-c75b-11e5-9865-92c8df6eae02.PNG)

스크롤이 생긴당께. overflow: hidden 적용해야하나?

**Comment by hj0212** [comment]
엉 히든걸어야겠다

**Comment by Rumo-Arf** [comment]
해봐.

**Comment by hj0212** [comment]
materialize.css의 tabs overflow:hidden 으로 수정완료
